name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Create lib directory
      run: mkdir -p lib
      
    - name: Download dependencies
      run: |
        # Download ModTheSpire
        curl -L -o lib/ModTheSpire.jar https://github.com/kiooeht/ModTheSpire/releases/latest/download/ModTheSpire.jar
        
        # Download BaseMod  
        curl -L -o lib/BaseMod.jar https://github.com/daviscook477/BaseMod/releases/latest/download/BaseMod.jar
        
        # desktop-1.0.jar needs to be downloaded

    - name: Check secret and decode
      run: |
        echo "Secret length: ${#DESKTOP_SECRET}"
        echo "$DESKTOP_SECRET" | base64  -d > lib/desktop-1.0.jar
        echo "File size: $(stat -c%s lib/desktop-1.0.jar
        file lib/desktop-1.0.jar
      env:
        DESKTOP_SECRET: ${{ secrets.DESKTOP_JAR_BASE64 }}
    
    - name: Build with Maven
      run: mvn clean package
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
