name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Create lib directory
      run: mkdir -p lib
      
    - name: Download ModTheSpire
      run: |
        echo "Downloading ModTheSpire..."
        curl -L -v -o lib/ModTheSpire.zip https://github.com/kiooeht/ModTheSpire/releases/download/v3.6.3/ModTheSpire.zip
        unzip ModTheSpire.zip
        cp ModTheSpire.jar lib/
        rm ModTheSpire.zip
        ls -la lib/ModTheSpire.jar
        
    - name: Download BaseMod
      run: |
        echo "Downloading BaseMod..."
        curl -L -v -o lib/BaseMod.jar https://github.com/daviscook477/BaseMod/releases/latest/download/BaseMod.jar
        ls -la lib/BaseMod.jar
        
    - name: Download desktop jar
      run: |
        echo "Downloading desktop jar..."
        curl -L -v -o lib/desktop-1.0.jar "https://github.com/YOURUSERNAME/YOURREPO/releases/download/deps/desktop-1.0.jar"
        ls -la lib/desktop-1.0.jar
        
    - name: Verify all files
      run: |
        echo "Contents of lib directory:"
        ls -la lib/
        echo "File types:"
        file lib/*.jar
    
    - name: Build with Maven
      run: mvn clean package
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
