name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Create lib directory
      run: mkdir -p lib
      
    - name: Download and setup dependencies
      run: |
        # Download ModTheSpire zip and extract
        echo "Downloading ModTheSpire zip..."
        curl -L -o ModTheSpire.zip https://github.com/kiooeht/ModTheSpire/releases/download/v3.6.3/ModTheSpire.zip
        
        # List contents first to see what's inside
        echo "Contents of ModTheSpire.zip:"
        unzip -l ModTheSpire.zip
        
        # Extract all files
        unzip ModTheSpire.zip
        
        # List extracted files
        echo "Extracted files:"
        ls -la
        
        # Find and copy the JAR file (it might not be named exactly ModTheSpire.jar)
        find . -name "*.jar" -exec cp {} lib/ \;
        
        # Clean up
        rm ModTheSpire.zip
        
        # Download BaseMod jar directly
        echo "Downloading BaseMod jar..."
        curl -L -o lib/BaseMod.jar https://github.com/daviscook477/BaseMod/releases/latest/download/BaseMod.jar
        
        # Download desktop jar from your Google Drive
        echo "Downloading desktop jar..."
        curl -L -o lib/desktop-1.0.jar "https://www.dropbox.com/scl/fi/yrwdy5hn4mapvaucmt0mm/desktop-1.0.jar?rlkey=h986plasqivds1cs959jdcgdq&st=5ka3t6l1&dl=1"
        
    - name: Verify all dependencies
      run: |
        echo "Contents of lib directory:"
        ls -la lib/
        echo "File types:"
        file lib/*.jar
    
    - name: Detailed JAR verification
      run: |
        echo "=== JAR File Analysis ==="
        for jar in lib/*.jar; do
          echo "--- $jar ---"
          ls -lh "$jar"
          file "$jar"
          echo "Can Java read it?"
          jar tf "$jar" | head -5 || echo "ERROR: Cannot read JAR contents"
          echo "ZIP test:"
          unzip -t "$jar" || echo "ERROR: JAR is corrupted"
          echo ""
        done
        
    - name: Test Maven dependency resolution
      run: |
        echo "Testing Maven dependency resolution..."
        mvn dependency:resolve -X | grep -E "(jar|ERROR|WARN)" || echo "Dependency resolution completed"
        
    - name: Try compile with detailed output
      run: |
        mvn clean compile -X -e

    - name: Build with Maven
      run: mvn clean package
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
